spring.application.name=TreinowAPI

# Configurações do Banco de Dados H2 em Memória
spring.datasource.url=jdbc:h2:mem:treinowdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Diz ao Hibernate/JPA para criar as tabelas automaticamente baseado nas suas Entidades (@Entity)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# Habilita o console web do H2 para você poder ver o banco pelo navegador, se quiser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console